server {
    listen 80;
    listen [::]:80;
    server_name raptor.com *.raptor.com crm.raptor.com app.raptor.com axiora.raptor.unaux.com raptor.unaux.com 98.94.227.211 raptor.local _;

    # ACME Challenge for Certbot renewal
    location /.well-known/acme-challenge/ {
        root /var/www/raptor/shared/acme;
    }

    # Redirect all HTTP requests to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name raptor.com *.raptor.com crm.raptor.com app.raptor.com axiora.raptor.unaux.com raptor.unaux.com 98.94.227.211 raptor.local _;

    client_max_body_size 64M;

    # SSL Certificates
    ssl_certificate /etc/letsencrypt/live/raptor/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/raptor/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/raptor/current/public;
    index index.php index.html;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }
}
